// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.4
//   protoc               v5.28.2
// source: assets/proto/test/example.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "example";

export interface ExampleRequest {
  query: string;
}

export interface ExampleResponse {
  result: string;
}

function createBaseExampleRequest(): ExampleRequest {
  return { query: "" };
}

export const ExampleRequest: MessageFns<ExampleRequest> = {
  encode(message: ExampleRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExampleRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExampleRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExampleRequest {
    return { query: isSet(object.query) ? globalThis.String(object.query) : "" };
  },

  toJSON(message: ExampleRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExampleRequest>, I>>(base?: I): ExampleRequest {
    return ExampleRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExampleRequest>, I>>(object: I): ExampleRequest {
    const message = createBaseExampleRequest();
    message.query = object.query ?? "";
    return message;
  },
};

function createBaseExampleResponse(): ExampleResponse {
  return { result: "" };
}

export const ExampleResponse: MessageFns<ExampleResponse> = {
  encode(message: ExampleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.result !== "") {
      writer.uint32(10).string(message.result);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExampleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExampleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.result = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExampleResponse {
    return { result: isSet(object.result) ? globalThis.String(object.result) : "" };
  },

  toJSON(message: ExampleResponse): unknown {
    const obj: any = {};
    if (message.result !== "") {
      obj.result = message.result;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExampleResponse>, I>>(base?: I): ExampleResponse {
    return ExampleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExampleResponse>, I>>(object: I): ExampleResponse {
    const message = createBaseExampleResponse();
    message.result = object.result ?? "";
    return message;
  },
};

export type ExampleServiceService = typeof ExampleServiceService;
export const ExampleServiceService = {
  getExample: {
    path: "/example.ExampleService/GetExample",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ExampleRequest) => Buffer.from(ExampleRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ExampleRequest.decode(value),
    responseSerialize: (value: ExampleResponse) => Buffer.from(ExampleResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => ExampleResponse.decode(value),
  },
} as const;

export interface ExampleServiceServer extends UntypedServiceImplementation {
  getExample: handleUnaryCall<ExampleRequest, ExampleResponse>;
}

export interface ExampleServiceClient extends Client {
  getExample(
    request: ExampleRequest,
    callback: (error: ServiceError | null, response: ExampleResponse) => void,
  ): ClientUnaryCall;
  getExample(
    request: ExampleRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ExampleResponse) => void,
  ): ClientUnaryCall;
  getExample(
    request: ExampleRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ExampleResponse) => void,
  ): ClientUnaryCall;
}

export const ExampleServiceClient = makeGenericClientConstructor(
  ExampleServiceService,
  "example.ExampleService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ExampleServiceClient;
  service: typeof ExampleServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
